name: CI

on:
  push:
    branches: [ main, teste-funcionalidade ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest fastapi httpx
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
